name: Gitflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - release
      - master

jobs:

### Validate ###
###############
  Gitflow:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

# verificar fuente
    - name: Checkout
      uses: actions/checkout@v3

# imprimiendo variables
    - name: Validating Branches
      run: |
        ./.github/workflows/validate.sh ${GITHUB_HEAD_REF} ${GITHUB_BASE_REF}

### security ###
################
  Security:
    name: Security
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

# verificar fuente
    - name: Checkout
      uses: actions/checkout@v3

# compilando imagenes de contenedores
    - name: Build Images
      run: |
        make base

# escaneando codigo estatico
    - name: Scan Code
      run: |
        make snyk_code SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}

# compilando codigo
    - name: Build Code
      run: |
        make build

# escaneando dependencias de codigo
    - name: Scan Dependencies
      run: |
        make snyk_test SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}