name: Gitflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - release
      - master

jobs:
  Build:
    name: Gitflow
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

# verificar fuente
    - name: Checkout
      uses: actions/checkout@v3

# imprimiendo variables
    - name: Print Envs
      run: |
        printenv