name: Gitflow

on:
  pull_request:
    branches:
      - release
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Security Tests
      run: |
           echo ${SNYK_TOKEN} > file.txt
           cat file.txt
           echo "hola" > hola.txt
           cat hola.txt